import { useState } from 'react';
import { RefreshCw, Bot, ChefHat, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

const initialMeals = [
  { id: 1, name: 'Protein Oatmeal', calories: 450, protein: 30, carbs: 50, fat: 10, type: 'Breakfast' },
  { id: 2, name: 'Grilled Chicken Salad', calories: 550, protein: 45, carbs: 20, fat: 25, type: 'Lunch' },
  { id: 3, name: 'Greek Yogurt & Berries', calories: 250, protein: 20, carbs: 30, fat: 5, type: 'Snack' },
];

export const DietPlanner = () => {
  const [meals, setMeals] = useState(initialMeals);
  const [preferences, setPreferences] = useState({ type: 'Balanced', calories: 2500 });
  const [isGenerating, setIsGenerating] = useState(false);

  const totalCalories = meals.reduce((acc, meal) => acc + meal.calories, 0);
  const totalProtein = meals.reduce((acc, meal) => acc + meal.protein, 0);
  const totalCarbs = meals.reduce((acc, meal) => acc + meal.carbs, 0);
  const totalFat = meals.reduce((acc, meal) => acc + meal.fat, 0);

  const handleRegenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setMeals([
        { id: 4, name: 'Avocado Toast & Eggs', calories: 500, protein: 25, carbs: 40, fat: 20, type: 'Breakfast' },
        { id: 5, name: 'Salmon & Quinoa', calories: 650, protein: 40, carbs: 45, fat: 25, type: 'Lunch' },
        { id: 6, name: 'Protein Shake', calories: 200, protein: 25, carbs: 5, fat: 2, type: 'Snack' },
        { id: 7, name: 'Lean Steak & Asparagus', calories: 700, protein: 50, carbs: 10, fat: 30, type: 'Dinner' },
      ]);
      setIsGenerating(false);
    }, 1500);
  };

  const removeMeal = (id: number) => {
    setMeals(meals.filter(m => m.id !== id));
  };

  return (
    <div className="max-w-7xl mx-auto w-full animate-slideUp space-y-8">
      {/* Header */}
      <div className="text-center mb-12">
        <h2 className="text-5xl md:text-7xl font-display mb-4">
          AI <span className="bg-primary text-primary-foreground px-4 inline-block transform skew-x-[-10deg]">Nutrition</span>
        </h2>
        <p className="text-xl max-w-2xl mx-auto font-bold opacity-80">
          Custom meal plans generated by our local LLM based on your metabolic rate.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Sidebar: Controls */}
        <div className="lg:col-span-1 p-6 border-4 border-border space-y-6 h-fit bg-card shadow-brutal">
          <h3 className="text-2xl font-display border-b-4 border-border pb-2 mb-4">Preferences</h3>

          <div>
            <label className="block font-bold uppercase text-xs mb-2 text-muted-foreground">Diet Type</label>
            <div className="flex flex-wrap gap-2">
              {['Balanced', 'Keto', 'Vegan', 'Paleo'].map(type => (
                <button
                  key={type}
                  onClick={() => setPreferences({ ...preferences, type })}
                  className={`px-4 py-2 font-bold uppercase text-sm border-2 border-border transition-colors ${
                    preferences.type === type ? 'bg-accent text-accent-foreground' : 'bg-card'
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block font-bold uppercase text-xs mb-2 text-muted-foreground">Daily Calorie Goal</label>
            <div className="flex items-center gap-4">
              <input
                type="range"
                min="1200"
                max="4000"
                step="50"
                value={preferences.calories}
                onChange={e => setPreferences({ ...preferences, calories: parseInt(e.target.value) })}
                className="w-full"
                style={{ accentColor: 'hsl(var(--accent))' }}
              />
              <span className="font-black text-xl w-20 text-right">{preferences.calories}</span>
            </div>
          </div>

          <Button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="w-full py-4 font-black text-xl uppercase tracking-widest hover:scale-105 transition-transform flex items-center justify-center gap-2 bg-secondary text-secondary-foreground border-4 border-border"
          >
            {isGenerating ? <RefreshCw className="animate-spin" /> : <Bot />}
            {isGenerating ? 'Cooking...' : 'Generate Plan'}
          </Button>
        </div>

        {/* Main Content: Meal List & Stats */}
        <div className="lg:col-span-2 space-y-8">
          {/* Stats Bar */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: 'Calories', val: totalCalories, max: preferences.calories, unit: 'kcal' },
              { label: 'Protein', val: totalProtein, max: 200, unit: 'g' },
              { label: 'Carbs', val: totalCarbs, max: 300, unit: 'g' },
              { label: 'Fat', val: totalFat, max: 80, unit: 'g' },
            ].map((stat, i) => (
              <div key={i} className="p-4 border-4 border-border text-center relative overflow-hidden bg-card">
                <div className="relative z-10">
                  <div className="text-xs font-bold uppercase text-muted-foreground">{stat.label}</div>
                  <div className="text-2xl font-black">
                    {stat.val} <span className="text-xs font-normal opacity-50">{stat.unit}</span>
                  </div>
                </div>
                <div className="absolute bottom-0 left-0 h-1 w-full">
                  <div className="h-full bg-accent" style={{ width: `${Math.min((stat.val / stat.max) * 100, 100)}%` }} />
                </div>
              </div>
            ))}
          </div>

          {/* Meal Cards */}
          <div className="space-y-4">
            {meals.map((meal, index) => (
              <div
                key={meal.id}
                className="group relative p-6 border-4 border-border flex flex-col md:flex-row items-start md:items-center justify-between gap-4 hover:-translate-y-1 transition-transform animate-slideUp bg-card"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 flex items-center justify-center border-2 border-border rounded-full bg-background">
                    <ChefHat className="w-6 h-6" />
                  </div>
                  <div>
                    <div className="text-xs font-bold uppercase text-muted-foreground tracking-widest">{meal.type}</div>
                    <h4 className="text-xl font-black uppercase">{meal.name}</h4>
                  </div>
                </div>

                <div className="flex items-center gap-6 w-full md:w-auto justify-between">
                  <div className="text-right">
                    <div className="font-black text-xl">{meal.calories} kcal</div>
                    <div className="text-xs font-mono text-muted-foreground">
                      P:{meal.protein}g C:{meal.carbs}g F:{meal.fat}g
                    </div>
                  </div>
                  <button onClick={() => removeMeal(meal.id)} className="p-2 hover:text-destructive transition-colors">
                    <Trash2 className="w-5 h-5" />
                  </button>
                </div>
              </div>
            ))}

            <button className="w-full py-4 border-4 border-dashed border-border flex items-center justify-center gap-2 font-bold uppercase hover:bg-muted transition-colors">
              <Plus className="w-5 h-5" /> Add Custom Meal
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
