// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aydbwgcphozgaunmoopu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZGJ3Z2NwaG96Z2F1bm1vb3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MTU5NzYsImV4cCI6MjA3OTM5MTk3Nn0.T-lWMta4hwuY_Bvnok_D7VlvrxF4AHZhI_y7if3lD8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});